### ISSUE TITLE
all the input arrays must have same number of dimensions

### ISSUE THREAD

**Issue by arshak** [christophM/rulefit#1]
Thanks for a great library.  When I try to run it on my dataset with 25 columns, I get the following error

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-fd9b1b37c1dd> in <module>()
      1 rf = RuleFit()
----> 2 rf.fit(X, y)

/Users/arshakn/anaconda/lib/python2.7/site-packages/rulefit/rulefit.pyc in fit(self, X, y, feature_names)
    266         ## concatenate original features and rules
    267         X_rules = self.rule_ensemble.transform(X)
--> 268         X_concat = np.concatenate((X, X_rules), axis=1)
    269 
    270         ## initialise Lasso

ValueError: all the input arrays must have same number of dimensions

**Comment by christophM** [comment]
Thanks for the feedback. 

When no rules are found, then the concatenation of the X and the rules fails. My best guess atm is, that this was the problem. It should be fixed now
