### ISSUE TITLE
import issue for rulefit

### ISSUE THREAD

**Issue by anupmandvariya** [christophM/rulefit#13]
Hi Christoph,

While importing rulefit module, I am getting below error. Can you please suggest?

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-10-5b07bd236b63> in <module>()
----> 1 import rulefit

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rulefit/__init__.py in <module>()
----> 1 from rulefit import RuleCondition, Rule, RuleEnsemble, RuleFit
      2 
      3 __all__ = ["rulefit"]

ImportError: cannot import name 'RuleCondition'

**Comment by christophM** [comment]
Thanks for the feedback, should work now.
