### ISSUE TITLE
Input variable importance

### ISSUE THREAD

**Issue by 1210768015** [christophM/rulefit#48]
![image](https://user-images.githubusercontent.com/66861694/182019930-390139ff-f842-45ec-92b2-05649e1b522f.png)
Is the importance of input variables in section 7 of the paper implemented in this project? I looked at the code and didn't find this part.

**Comment by chriswbartley** [comment]
yes, it is implemented in get_feature_importance(), line 654, 655:
            mk_array = features_in_rule[feature_rk]
            feature_imp.append(float(linear_imp + (rule_imp/mk_array).sum())

cheers

**Comment by 1210768015** [comment]
I found this part, thank you very much!
